#!/bin/bash
echo "=> Building otrrentapi --build args"
docker build --build-arg FLASK_DEPLOY_MODULE=otrrentapi --build-arg FLASK_DEPLOY_CALLABLE=app --build-arg FLASK_DEPLOY_PORT=8001 -t $IMAGE_NAME .